In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
customer=pd.read_csv("customer.csv")
sales=pd.read_csv("sales.csv")
products=pd.read_csv("products.csv")
df2=sales.merge(products, on='product_id', how='left')
df=df2.merge(customer, on='customer_id', how='left')

In [2]:
df.shape

(5908, 34)

In [3]:
df.columns

Index(['serial_number', 'order_id', 'order_date', 'delivery_date',
       'time_of_order', 'time_of_delivery', 'delivery_mode', 'sales_agent',
       'payment_mode', 'delivery_rating', 'product_id', 'customer_id', 'sales',
       'quantity', 'percent_discount', 'profit', 'Product_name', 'category',
       'sub_category', 'color', 'brand_name', 'average_rating',
       'reviews_count', 'customer_name', 'customer_age', 'Customer_type',
       'country', 'city', 'state', 'SMS_Marketing', 'Email_Marketing',
       'Membership_type', 'Joining_date', 'App_Downloaded'],
      dtype='object')

In [4]:
df.customer_id.value_counts(sort=True,
                            #normalize=True
                           )

customer_id
WPP-4399    26
ENW-6578    22
ZOS-1180    21
AFP-8127    21
JCM-4112    21
            ..
POT-8365     1
RNN-4548     1
BNR-3660     1
ACL-6790     1
MVV-6042     1
Name: count, Length: 790, dtype: int64

In [5]:
group_df=df.groupby(['customer_id','customer_name']).sum().reset_index()
group_df.sort_values('quantity',ascending=False,inplace=True)
group_df

,customer_id,customer_name,serial_number,order_id,order_date,delivery_date,time_of_order,time_of_delivery,delivery_mode,sales_agent,...,customer_age,Customer_type,country,city,state,SMS_Marketing,Email_Marketing,Membership_type,Joining_date,App_Downloaded
784,WPP-4399,William Brown,76664,C-46097-31911C-82414-31911C-62003-1209C-85522-...,15-03-201917-03-201904-01-202005-01-202003-09-...,19-03-201924-03-201909-01-202010-01-202008-09-...,11:41 AM11:49 AM9:39 AM9:07 AM9:29 AM5:29 PM5:...,5:19 PM9:37 AM9:45 AM3:10 PM1:32 PM2:55 PM1:02...,Standard ClassStandard ClassStandard ClassStan...,Edward RuffaloTom RennerJohn WickDave Brockman...,...,988,City ClubCity ClubCity ClubCity ClubCity ClubC...,United StatesUnited StatesUnited StatesUnited ...,PhiladelphiaPhiladelphiaPhiladelphiaPhiladelph...,PennsylvaniaPennsylvaniaPennsylvaniaPennsylvan...,NONONONONONONONONONONONONONONONONONONONONONONO...,YESYESYESYESYESYESYESYESYESYESYESYESYESYESYESY...,BasicBasicBasicBasicBasicBasicBasicBasicBasicB...,16-03-202016-03-202016-03-202016-03-202016-03-...,NONONONONONONONONONONONONONONONONONONONONONONO...
258,EIC-1982,Emily Phan,71754,D-59201-91912D-18433-91911D-55766-9199D-70366-...,08-09-201914-09-201920-09-201927-09-201913-12-...,12-09-201914-09-201924-09-201903-10-201917-12-...,12:40 PM11:23 AM9:31 AM12:09 PM5:57 PM11:16 AM...,1:58 PM1:56 PM5:47 PM10:24 AM1:06 PM10:49 AM12...,Standard ClassSame DayStandard ClassStandard C...,Tom RennerChris JrNora ZypernJohn McCarthyAnth...,...,798,City ClubCity ClubCity ClubCity ClubCity ClubC...,United StatesUnited StatesUnited StatesUnited ...,ChicagoChicagoChicagoChicagoChicagoChicagoChic...,IllinoisIllinoisIllinoisIllinoisIllinoisIllino...,NONONONONONONONONONONONONONONONONONONONONO,NONONONONONONONONONONONONONONONONONONONONO,SilverSilverSilverSilverSilverSilverSilverSilv...,30-05-202030-05-202030-05-202030-05-202030-05-...,YESYESYESYESYESYESYESYESYESYESYESYESYESYESYESY...
555,NIC-1732,Noel Staavos,52860,D-12299-1199D-76592-32014D-31508-32014D-63402-...,25-01-201914-03-202020-03-202029-03-202030-03-...,31-01-201918-03-202023-03-202004-04-202003-04-...,9:25 AM2:22 PM2:47 PM2:34 PM1:28 PM1:24 PM12:5...,10:39 AM11:15 AM9:33 AM11:14 AM9:10 AM5:11 PM9...,Standard ClassStandard ClassFirst ClassStandar...,Nora ZypernNora ZypernTom RennerJohn McCarthyD...,...,666,State ClubState ClubState ClubState ClubState ...,United StatesUnited StatesUnited StatesUnited ...,ChicagoChicagoChicagoChicagoChicagoChicagoChic...,IllinoisIllinoisIllinoisIllinoisIllinoisIllino...,NONONONONONONONONONONONONONONONONONO,YESYESYESYESYESYESYESYESYESYESYESYESYESYESYESY...,GoldGoldGoldGoldGoldGoldGoldGoldGoldGoldGoldGo...,28-07-201928-07-201928-07-201928-07-201928-07-...,YESYESYESYESYESYESYESYESYESYESYESYESYESYESYESY...
268,ENW-6578,Edward Hooks,71571,C-91961-41917D-37792-62012D-90782-62012C-82804...,09-04-201918-06-202025-06-202008-03-202117-03-...,12-04-201923-06-202001-07-202012-03-202117-03-...,5:35 PM12:43 PM12:46 PM3:21 PM3:55 PM3:54 PM10...,1:45 PM12:28 PM11:18 AM5:45 PM4:26 PM11:56 AM9...,Standard ClassStandard ClassStandard ClassStan...,Tom RennerDave BrockmanTom RennerRobert PaigeJ...,...,968,State ClubState ClubState ClubState ClubState ...,United StatesUnited StatesUnited StatesUnited ...,WatertownWatertownWatertownWatertownWatertownW...,New YorkNew YorkNew YorkNew YorkNew YorkNew Yo...,NONONONONONONONONONONONONONONONONONONONONONO,NONONONONONONONONONONONONONONONONONONONONONO,SilverSilverSilverSilverSilverSilverSilverSilv...,27-10-201927-10-201927-10-201927-10-201927-10-...,YESYESYESYESYESYESYESYESYESYESYESYESYESYESYESY...
507,MMD-7588,Maribeth Schnelling,40252,C-76472-4199C-64273-32016C-32215-32016C-50439-...,24-04-201912-03-202013-03-202003-10-202009-10-...,29-04-201917-03-202015-03-202006-10-202013-10-...,9:06 AM4:52 PM4:04 PM2:27 PM1:30 PM4:18 PM4:21...,12:33 PM5:52 PM10:36 AM10:33 AM12:20 PM2:07 PM...,Standard ClassStandard ClassFirst ClassSecond ...,Robert PaigeNora ZypernJohn WickJohn McCarthyJ...,...,935,City ClubCity ClubCity ClubCity ClubCity ClubC...,United StatesUnited StatesUnited StatesUnited ...,DetroitDetroitDetroitDetroitDetroitDetroitDetr...,MichiganMichiganMichiganMichiganMichiganMichig...,NONONONONONONONONONONONONONONONONO,NONONONONONONONONONONONONONONONONO,SilverSilverSilverSilverSilverSilverSilverSilv...,06-07-202006-07-202006-07-202006-07-202006-07-...,YESYESYESYESYESYESYESYESYESYESYESYESYESYESYESY...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,MTD-4082,Michael Oakman,1649,C-65074-102210,20-10-2022,27-10-2022,10:19 AM,11:15 AM,Standard Class,Robert Hemsworth,...,35,General customer,United States,Dallas,Texas,YES,NO,Basic,20-10-2019,YES
319,HFJ-4022,Heather Jas,4666,D-16199-62212,21-06-2022,25-06-2022,12:39 PM,9:33 AM,Standard Class,Robert Paige,...,32,General customer,United States,Jacksonville,Florida,YES,NO,Gold,30-03-2020,NO
54,ATH-2496,Anna Chung,605,C-67961-32116,20-03-2021,24-03-2021,4:46 PM,5:18 PM,Standard Class,John Wick,...,30,General customer,United States,Huntsville,Texas,NO,YES,Silver,23-05-2020,YES
129,CCS-5209,Clay Cheatham,1998,C-40280-112214,23-11-2022,24-11-2022,2:37 PM,5:52 PM,First Class,Chris Jr,...,42,General customer,United States,San Francisco,California,NO,NO,Basic,01-04-2020,NO
10,ACL-6790,Anthony O'Donnell,3212,C-40333-71910,05-07-2019,08-07-2019,10:46 AM,5:53 PM,First Class,John Wick,...,66,General customer,United States,Los Angeles,California,NO,YES,Basic,05-02-2019,YES

In [6]:
loyal_cust=group_df.loc[:,['customer_name','quantity']].iloc[:11,:]
loyal_cust

           customer_name  quantity
784        William Brown        93
258           Emily Phan        91
555         Noel Staavos        84
268         Edward Hooks        82
507  Maribeth Schnelling        82
349             John Lee        79
590           Paul Prost        79
676    Steven Cartwright        77
611            Pete Kriz        77
172  Chloris Kastensmidt        77
338           Joe Elijah        76

In [ ]:
plt.bar(x=loyal_cust.customer_name,height=loyal_cust.quantity)
plt.xlabel('Customers Name')
plt.ylabel('Quantity Purchased')
plt.title('Top 10 Customers')
plt.show()